flask==0.12.2
plotly==2.2.1
pandas==0.20.3
scipy==0.19.1
scikit-learn==0.19.1
dash==0.21.1    # may need 22.0rc2 for bootstrap?
dash-renderer==0.12.1
dash_html_components==0.11.0rc5  # for bootstrap
dash-core-components==0.22.1
dash-table-experiments==0.6.0
dash-dangerously-set-inner-html==0.0.1
