name: reduct-dev
channels:
  - conda-forge
dependencies:
 - scikit-learn=0.20.0
 - pandas=0.23.4
 - numpy=1.15.4
 - flask=1.0.2
 - scipy=1.1.0
 - plotly=3.4.1
 - dash=0.30.0
 - dash-renderer=0.15.0
 - dash-core-components=0.38.0
 - dash-html-components=0.13.2
 - pip:
   - dash-table-experiments
   - flask-caching
